import * as colors from '@radix-ui/colors'

const transformColor = (obj) =>
  Object.fromEntries(
    Object.entries(obj).map(([k, v]) => [k.replace(/(\d+)/, '-$1'), v])
  )

const color = (c) => transformColor(colors[c])

module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'selector',
  theme: {
    // extend: {
    //   colors: {
    //     sand: {
    //       1: 'var(--sand-1)',
    //       2: 'var(--sand-2)',
    //       3: 'var(--sand-3)',
    //       4: 'var(--sand-4)',
    //       5: 'var(--sand-5)',
    //       6: 'var(--sand-6)',
    //       7: 'var(--sand-7)',
    //       8: 'var(--sand-8)',
    //       9: 'var(--sand-9)',
    //       10: 'var(--sand-10)',
    //       11: 'var(--sand-11)',
    //       12: 'var(--sand-12)',
    //       a1: 'var(--sand-a1)',
    //       a2: 'var(--sand-a2)',
    //       a3: 'var(--sand-a3)',
    //       a4: 'var(--sand-a4)',
    //       a5: 'var(--sand-a5)',
    //       a6: 'var(--sand-a6)',
    //       a7: 'var(--sand-a7)',
    //       a8: 'var(--sand-a8)',
    //       a9: 'var(--sand-a9)',
    //       a10: 'var(--sand-a10)',
    //       a11: 'var(--sand-a11)',
    //       a12: 'var(--sand-a12)',
    //     },
    //     slate: {
    //       1: 'var(--slate-1)',
    //       2: 'var(--slate-2)',
    //       3: 'var(--slate-3)',
    //       4: 'var(--slate-4)',
    //       5: 'var(--slate-5)',
    //       6: 'var(--slate-6)',
    //       7: 'var(--slate-7)',
    //       8: 'var(--slate-8)',
    //       9: 'var(--slate-9)',
    //       10: 'var(--slate-10)',
    //       11: 'var(--slate-11)',
    //       12: 'var(--slate-12)',
    //       a1: 'var(--slate-a1)',
    //       a2: 'var(--slate-a2)',
    //       a3: 'var(--slate-a3)',
    //       a4: 'var(--slate-a4)',
    //       a5: 'var(--slate-a5)',
    //       a6: 'var(--slate-a6)',
    //       a7: 'var(--slate-a7)',
    //       a8: 'var(--slate-a8)',
    //       a9: 'var(--slate-a9)',
    //       a10: 'var(--slate-a10)',
    //       a11: 'var(--slate-a11)',
    //       a12: 'var(--slate-a12)',
    //     },
    //     // ...color('gray'),
    //     // ...color('grayA'),
    //     // // ...color('grayDark'),
    //     // // ...color('grayDarkA'),
    //     // ...color('mauve'),
    //     // ...color('mauveA'),
    //     // // ...color('mauveDark'),
    //     // // ...color('mauveDarkA'),
    //     // // ...color('slate'),
    //     // // ...color('slateA'),
    //     // // ...color('slateDark'),
    //     // // ...color('slateDarkA'),
    //     // ...color('sage'),
    //     // ...color('sageA'),
    //     // // ...color('sageDark'),
    //     // // ...color('sageDarkA'),
    //     // ...color('olive'),
    //     // ...color('oliveA'),
    //     // // ...color('oliveDark'),
    //     // // ...color('oliveDarkA'),
    //     // ...color('sand'),
    //     // ...color('sandA'),
    //     // // ...color('sandDark'),
    //     // // ...color('sandDarkA'),
    //     // ...color('tomato'),
    //     // ...color('tomatoA'),
    //     // // ...color('tomatoDark'),
    //     // // ...color('tomatoDarkA'),
    //     // ...color('red'),
    //     // ...color('redA'),
    //     // // ...color('redDark'),
    //     // // ...color('redDarkA'),
    //     // ...color('ruby'),
    //     // ...color('rubyA'),
    //     // // ...color('rubyDark'),
    //     // // ...color('rubyDarkA'),
    //     // ...color('crimson'),
    //     // ...color('crimsonA'),
    //     // // ...color('crimsonDark'),
    //     // // ...color('crimsonDarkA'),
    //     // ...color('pink'),
    //     // ...color('pinkA'),
    //     // // ...color('pinkDark'),
    //     // // ...color('pinkDarkA'),
    //     // ...color('plum'),
    //     // ...color('plumA'),
    //     // // ...color('plumDark'),
    //     // // ...color('plumDarkA'),
    //     // ...color('purple'),
    //     // ...color('purpleA'),
    //     // // ...color('purpleDark'),
    //     // // ...color('purpleDarkA'),
    //     // ...color('violet'),
    //     // ...color('violetA'),
    //     // // ...color('violetDark'),
    //     // // ...color('violetDarkA'),
    //     // ...color('iris'),
    //     // ...color('irisA'),
    //     // // ...color('irisDark'),
    //     // // ...color('irisDarkA'),
    //     // ...color('indigo'),
    //     // ...color('indigoA'),
    //     // // ...color('indigoDark'),
    //     // // ...color('indigoDarkA'),
    //     // ...color('blue'),
    //     // ...color('blueA'),
    //     // // ...color('blueDark'),
    //     // // ...color('blueDarkA'),
    //     // ...color('cyan'),
    //     // ...color('cyanA'),
    //     // // ...color('cyanDark'),
    //     // // ...color('cyanDarkA'),
    //     // ...color('teal'),
    //     // ...color('tealA'),
    //     // // ...color('tealDark'),
    //     // // ...color('tealDarkA'),
    //     // ...color('jade'),
    //     // ...color('jadeA'),
    //     // // ...color('jadeDark'),
    //     // // ...color('jadeDarkA'),
    //     // ...color('green'),
    //     // ...color('greenA'),
    //     // // ...color('greenDark'),
    //     // // ...color('greenDarkA'),
    //     // ...color('grass'),
    //     // ...color('grassA'),
    //     // // ...color('grassDark'),
    //     // // ...color('grassDarkA'),
    //     // ...color('bronze'),
    //     // ...color('bronzeA'),
    //     // // ...color('bronzeDark'),
    //     // // ...color('bronzeDarkA'),
    //     // ...color('gold'),
    //     // ...color('goldA'),
    //     // // ...color('goldDark'),
    //     // // ...color('goldDarkA'),
    //     // ...color('brown'),
    //     // ...color('brownA'),
    //     // // ...color('brownDark'),
    //     // // ...color('brownDarkA'),
    //     // ...color('orange'),
    //     // ...color('orangeA'),
    //     // // ...color('orangeDark'),
    //     // // ...color('orangeDarkA'),
    //     // ...color('amber'),
    //     // ...color('amberA'),
    //     // // ...color('amberDark'),
    //     // // ...color('amberDarkA'),
    //     // ...color('yellow'),
    //     // ...color('yellowA'),
    //     // // ...color('yellowDark'),
    //     // // ...color('yellowDarkA'),
    //     // ...color('lime'),
    //     // ...color('limeA'),
    //     // // ...color('limeDark'),
    //     // // ...color('limeDarkA'),
    //     // ...color('mint'),
    //     // ...color('mintA'),
    //     // // ...color('mintDark'),
    //     // // ...color('mintDarkA'),
    //     // ...color('sky'),
    //     // ...color('skyA'),
    //     // // ...color('skyDark'),
    //     // // ...color('skyDarkA'),
    //   },
    // },
  },
  plugins: [],
}
